### ISSUE TITLE
Change NavBar color

### ISSUE THREAD

**Issue by nisalrenuja** [nisalrenuja/ITP21F_08#34]

**Comment by Buddhima-JD3** [comment]
#35 Check this

**Comment by Buddhima-JD3** [comment]
![Screenshot 2021-07-31 152036](https://user-images.githubusercontent.com/77372038/127736083-2c6dc0e9-79e9-45ce-ad94-d586a52c5036.png)

**Comment by nisalrenuja** [comment]
well done
